development:
  adapter: postgresql
  database: terranull_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: terranull_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: terranull
  pool: 5
  timeout: 5000
